---

version: 1

disable_existing_loggers: False

formatters:
 simple:
  format: '%(asctime)s-%(levelname)s-|%(funcName)s|%(lineno)d|: %(message)s'

handlers:
 console:
  class: logging.StreamHandler
  level: INFO
  formatter: simple
  stream: ext://sys.stdout
 ccrotatingfile:
  class: cloghandler.ConcurrentRotatingFileHandler
  level: DEBUG
  formatter: simple
  filename: algopox.log
  maxBytes: 1048576
  backupCount: 10
  encoding: utf8
loggers:
 simpleExample:
  level: DEBUG
  handlers: [console]
  propagate: no
root:
 level: DEBUG
 handlers: [console,ccrotatingfile]



